[package]
name = "pyth_agent"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.55"
serde = { version = "1.0.136", features = [ "derive" ] }
async-trait = "0.1.52"
warp = { version = "0.3.1", features = [ "websocket" ] }
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1.1"
futures-util = { version = "0.3", default-features = false, features = ["sink"] }
jrpc = "0.4.1"
serde_json = "1.0.79"
tracing = "0.1.31"
